section_categories = {
    "TITLE": [
        "name of the study",
        "title",
        "full title",
    ],
    "JUSTIFICATION": [
        "background",
        "scientific justification",
        "rationale",
        "main backgrounds",
    ],
    "OBJECTIVE": [
        "objectives",
        "main objective and primary endpoint",
        "main end-points",
        "primary objective",
        "primary objectives",
        "criteria of assessment",
        "primary objective and assessment criterion",
        "objective and primary endpoint",
        "objectives and secondary endpoints",
        "secondary objectives",
        "secondary objectives and endpoints",
        "secondary objectives and assessment criteria",
        "secondary end-points",
        "study endpoints",
        "study objectives",
        "evaluation criteria",
        "Questions asked in the CAALL-F01 protocol",
    ],
    "DESIGN": [
        "Study Design",
        "design / phase / category",
        "design of the study",
        "design of the trial",
        "experimental design",
        "diagnostic method",
        "reference diagnostic method",
        "Scope of the trial",
        "ancillary study",
        "type of study",
    ],
    "INCLUSION CRITERIA": [
        "inclusion criteria",
        "preinclusion criteria",
        "graall-2014/b inclusion criteria",
        "graall-quest inclusion criteria",
        "inclusion criteria observational phase: (n°1,2,3,4,6,7,8,9) interventional phase: (n°1,2,3,4,5,6,7,8).",
        "inclusion criteria   ",
        "inclusion criteria of donors",
        "inclusion criteria of patients",
        "population concerned",
        "population involved",
        "population of study participants",
        "population of trial subjects",
        "Indication",
    ],
    "EXCLUSION CRITERIA": [
        "graall-2014/b non inclusion criteria",
        "graall-quest non inclusion criteria",
        "non-preinclusion and non-inclusion criteria",
        "non-inclusion criteria",
        "non inclusion criteria",
        "exclusion criteria observational phase: (n°1,2,3) interventional phase: (n°:1,2,3,4,5,6,7,8).",
        "exclusion criteria",
        "exclusion criteria :",
        "exclusion criteria of patients",
        "exclusion criterion",
    ],
    "INTERVENTION": [
        "reference treatment",
        "transplant modalities",
        "transplant modalities medical product provided by the Sponsor",
        "transplantation modalities",
        "transplants modalities",
        "treatment (transplant modalities)",
        "treatment being tested",
        "treatment",
        "benchmark treatment",
        "comparator strategy and treatment",
        "comparator treatment",
        "concomitant treatments",
        "experimental treatment",
        "experimental drug prescription outside ma",
        "experimental drugs prescription according to ma",
        "experimental group",
        "investigational medicinal product(s)",
        "investigational drug",
        "investigational medicinal product",
        "medicinal product and auxiliairy medicinal products",
        "investigational medicinal products",
        "investigational strategy and medicinal product(s)",
        "investigational medicinal product and auxiliairy medicinal products",
        "Study Intervention",
        "Study intervention",
        "chemotherapy",
        "Challenge agents",
        "comparator",
        "comparator arm",
    ],
    "STATISTICS": [
        "statistical justification of sample size",
        "statistical analysis",
        "statistical power and sample size justification:",
        "first interim analysis",
        "sample size",
    ],
}

rephrasing_model = "gpt-4o-2024-08-06"

dev_origins = [
    "http://localhost:8000",  # localhost backend only
    "http://127.0.0.1:8000",
    "http://localhost:5173",  # frontend dev server
    "http://127.0.0.1:5173/",
]
